name: Build jobs
# Triggered by changes in code-specific or job-specific files

on:
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/*.yml'
      - 'pyproject.toml'
      - 'tox.ini'
      - '!docs/**'
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Generic pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install pre-commit
      - run: SKIP=mypy pre-commit run --all-files

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install pre-commit
      - run: pre-commit run mypy --all-files

  tests:
    name: tests_${{ matrix.tox_job }}
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        include:
          - tox_job: py39
            python: "3.9"
            os_version: "ubuntu-latest"
          - tox_job: py39-no_pycurl
            python: "3.9"
            os_version: "ubuntu-latest"
          - tox_job: pypy3-no_pycurl
            python: "pypy-3.10"
            os_version: "ubuntu-latest"
          - tox_job: vcr_431
            python: "3.9"
            os_version: "ubuntu-latest"
          - tox_job: py310
            python: "3.10"
            os_version: "ubuntu-latest"
          - tox_job: py311
            python: "3.11"
            os_version: "ubuntu-latest"
          - tox_job: py312
            python: "3.12"
            os_version: "ubuntu-latest"
          - tox_job: py313
            python: "3.13"
            os_version: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: pip install tox coverage

      - run: sudo apt update && sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Run ${{ matrix.tox_job }} tox job
        run: tox -e ${{ matrix.tox_job }}

      - run: coverage combine
      - run: coverage report
      - run: coverage xml -i

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.3.1
        with:
          file: ./coverage.xml
